### ISSUE TITLE
Initialisierung fail 

### ISSUE THREAD

**Issue by mastersound2** [Kiriki-liszt/JS_Inflator#17]
Windows: Sobald Inflator 1.6 Oversampling im Linear Mode verwendet, wird es beim nächsten Projekt-laden nicht aktiv und muss als neue Instanz dem Projekt hizugefügt werden. Im Minphasen Mode kein Problem.

DAW: Samplitude ProX / Sequoia

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for your interest and long waiting.  
The crashing issue happened because I tried to resample whole buffer block, allocating (8+4+2+1) * 2 channels * (input/output buffers).  
So while allocating such big memory buffer, if it was not able to allocate, it crashes.  
Just fixed that issue in the latest beta release, so check it out =)
Have a nice day!

**Comment by mastersound2** [comment]
Hallo, nach ersten Tests mit der 1.7-2 scheint es stabil mit dem Lin Mode 2,4,8 zu funktionieren. Ich hoffe, die altern. GUI kommt auch noch hinzu?
Ich wünsche weiterhin frohes Schaffen !

**Comment by Kiriki-liszt** [comment]
Thank you! GUIs will be added in stable release, after beta releases.
Have a nice day!
